### ISSUE TITLE
Hunter Job

### ISSUE THREAD

**Issue by AsmoEum** [Smolwong/Smolcraft#11]
Does not include the new trial's mobs (the breeze and the bogged)

Hunter also does not include:
Magma Cube
Piglin
Piglin Brute
Pillager 
Ravager
Evoker
~Warden~
Zoglin
Wither Skelly
Vex
Vindicator
Witch
Zombie Villager
Slime
Elder Guardian 
Hoglin
Endermite

Passive Mobs(also huntable...):
Mooshroom
Skeleton Horse
Squid
Cod
Camel
Bat
Horse
Parrot
Ocelot
Muel
Glow Squid
Pufferfish
Salmon
Wandering trader
Horse

Neutral mobs:
Goats 
Trader LIama
Liama
Fox
Wolfs
Polarbears
Dolphins
Bees 
Pandas
Iron Golems

Also why are we getting paid $3.94 to kill a Giant, WTF is a giant... a 2009 test mob with no Ai and the look of a... giant zombie who does not naturally spawn.

**Comment by Smolwong** [comment]
Added:

Magma Cube
Piglin
Piglin Brute
Pillager
Ravager
Evoker
Warden
Zoglin
Wither Skelly
Vex
Vindicator
Witch
Zombie Villager
Slime
Elder Guardian
Hoglin
Endermite
Mooshroom
Skeleton Horse
Cod
Camel
Bat
Horse
Parrot
Ocelot
Muel
Glow Squid
Pufferfish
Salmon
Wandering trader
Goats
Trader LIama
Liama
Fox
Wolfs
Polarbears
Dolphins
Bees
Pandas

Squid and iron golem already in the job.
