### ISSUE TITLE
Fishing job

### ISSUE THREAD

**Issue by AsmoEum** [Smolwong/Smolcraft#3]
Cod = $2.29 1.94xp
Tropical Fish = $2.29 1.94xp
![image](https://github.com/user-attachments/assets/bc04633b-12a5-4e11-a6d2-166e0d60511f)

**Comment by Smolwong** [comment]
Works as intended.

**Comment by Smolwong** [comment]
Changing close type

**Comment by Smolwong** [comment]
Closed as Not Planned
