### ISSUE TITLE
Towny 

### ISSUE THREAD

**Issue by AsmoEum** [Smolwong/Smolcraft#7]
Very clunky with the permissions for deciding who can do what on what, as well as the menu having redundant features such as "friends" which has no actual use nor function. 
Moreover, the amount of chunks given for the massive size of the world is quite restricting upon initial experiments.

**Comment by Smolwong** [comment]
> "Very clunky with the permissions for deciding who can do what on what, as well as the menu having redundant features such as "friends" which has no actual use nor function."
RTFM: https://github.com/TownyAdvanced/Towny/wiki or https://www.youtube.com/playlist?list=PLvzvmyk0uI0WsLf4iyJZRhD_T2e-ANCmE

TownyMenu is lacking in love, not much that I can do there, but its something at least.

> "Moreover, the amount of chunks given for the massive size of the world is quite restricting upon initial experiments."
Doubled town chunks, added 10 chunks to newly created towns.
