### ISSUE TITLE
Job penalties 

### ISSUE THREAD

**Issue by AsmoEum** [Smolwong/Smolcraft#9]
Aint no way there are 22 people currently dragging down the mining industry when I know for a fact being I am the only one online actually mining, crippling me and especially any new people all due to nonexistent people.

**Comment by Smolwong** [comment]
Temporarily removed job bonus and penalty, cleaned up database, added 24 hour job purge.

Future plan is to re-enable job bonus and penalty once playerbase grows large enough to not cause a massive change in %.
